apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
   release: "stable"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 18.218.27.62
    path: "/nfs"
