kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      release: "stable"
