apiVersion: v1
kind: Service
metadata:
  name: sonar-service
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: sonar-port
    protocol: TCP
  selector:
    app: sonar
  type: NodePort
